server:
  port: 8080

spring:
  application:
    name: collector-service

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081

kafka:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1