server:
  port: 8080

spring:
  application:
    name: collector-service
  kafka:

    bootstrap-servers: localhost:9092
    producer:
      properties:

        schema.registry.url: http://schema-registry:8081

kafka:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1