server:
  port: 8080

spring:
  application:
    name: collector-service
    kafka:
      producer:
        value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

kafka:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1