name: Smart Home Tech Tests

on:
  workflow_dispatch:
    inputs:
      verbose_mode:
        description: "Включить подробные логи во время тестов"
        required: false
        default: false
        type: boolean
      print_logs:
        description: "Включить вывод логов в консоль"
        required: false
        default: false
        type: boolean
  pull_request:

jobs:
  build:
    services:
      kafka:
        image: confluentinc/confluent-local:7.4.3
        ports:
          - 9092:9092
        environment:
          KAFKA_NODE_ID: 1
          KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
          KAFKA_PROCESS_ROLES: 'broker,controller'
          KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
          KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
          CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      schema-registry:
        image: confluentinc/cp-schema-registry:7.4.3
        ports:
          - 8081:8081
        environment:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
          SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

    uses: yandex-praktikum/plus-smart-home-tech/.github/workflows/api-tests.yml@ci
    with:
      verbose_mode: ${{ inputs.verbose_mode }}
      print_logs: ${{ inputs.print_logs }}